### ISSUE TITLE
Result image's quality is poor

### ISSUE THREAD

**Issue by pengcm** [zhangmozhe/microshift_compression#1]
When I run "example_testbench_low_power.m" with" compression mode=1" and keep all the other settings unchanged, the result image's black, with compression ratio = 7.8904,psnr = 19.8806,ssim = 0.27386. 
![results](https://user-images.githubusercontent.com/11424275/92543526-4d9a9980-f27e-11ea-94ed-27d106a4d307.png)

**Comment by zhangmozhe** [comment]
Have you tried to test on our test images?

**Comment by pengcm** [comment]
> Have you tried to test on our test images?

Yes,  the posted image is the result of your test image 'input_images/elaine.bmp' with compression mode=1 and decompression mode=1.
